/**
 * @file src/types/index.ts
 * @description Global TypeScript type definitions and interfaces for the
 *              AR Indoor Navigation & 3D Building Mapping System.
 *
 * Phase 2 additions:
 *  - ScanStatus enum (not_started | in_progress | completed)
 *  - BuildingType enum (college | school | mall | hospital | office | other)
 *  - Expanded Building interface (address, buildingType, scanStatus, thumbnailUri)
 *  - UpdateBuildingPayload type
 *  - BuildingDetails navigation param
 *  - Expanded BuildingState (updateBuilding, deleteBuilding, getBuildingById)
 *
 * Phase 3 additions:
 *  - Camera navigation param
 *  - Re-export camera types
 *
 * Phase 4 additions:
 *  - ARStatus navigation param
 *  - Re-export AR types
 *
 * Phase 5A additions:
 *  - ARDiagnostics navigation param
 *  - Re-export AR Native types
 *
 * Phase 5B.1 additions:
 *  - ScanSession navigation param
 *  - Re-export ScanSession types
 *
 * Phase 5C.3 additions:
 *  - PlaneDiagnostics navigation param
 *  - Re-export Plane types
 *
 * Phase 5C.4 additions:
 *  - Walkthrough navigation param
 *  - Re-export Walkthrough types
 */

// ---------------------------------------------------------------------------
// Navigation
// ---------------------------------------------------------------------------

/**
 * Root stack navigator param list.
 */
export type RootStackParamList = {
  Splash: undefined;
  Main: undefined;
};

/**
 * Main stack navigator param list.
 * Phase 2: Added BuildingDetails with a required buildingId param.
 * Phase 3: Added Camera route.
 * Phase 4: Added ARStatus route.
 * Phase 5A: Added ARDiagnostics route.
 * Phase 5B.1: Added ScanSession route.
 * Phase 5C.3: Added PlaneDiagnostics route.
 * Phase 5C.4: Added Walkthrough route.
 */
export type MainStackParamList = {
  Home: undefined;
  Buildings: undefined;
  CreateBuilding: { editId?: string } | undefined;
  BuildingDetails: { buildingId: string };
  Camera: { buildingId?: string } | undefined;
  ARStatus: undefined;
  ARDiagnostics: undefined;
  PlaneDiagnostics: undefined;
  ScanSession: { buildingId?: string; buildingName?: string; floor?: number } | undefined;
  Walkthrough: { buildingId?: string; buildingName?: string; floor?: number } | undefined;
  UnifiedScan: { buildingId?: string; buildingName?: string; floor?: number } | undefined;
  CoverageDiagnostics: undefined;
  ScanValidation: undefined;
  ScanFinalizationSuccess: { buildingId?: string; buildingName?: string } | undefined;
  DeveloperOptions: undefined;
  Settings: undefined;
  About: undefined;
};

// ---------------------------------------------------------------------------
// Building — Enums & Types
// ---------------------------------------------------------------------------

/**
 * Scan status of a building.
 * Drives the status badge displayed on BuildingCard and BuildingDetails.
 */
export type ScanStatus = 'not_started' | 'in_progress' | 'completed';

/**
 * Category / type of the indoor building.
 * Used for filtering and display in future phases.
 */
export type BuildingType =
  | 'college'
  | 'school'
  | 'mall'
  | 'hospital'
  | 'office'
  | 'other';

/**
 * Legacy status kept for Phase 1 compatibility.
 * Use ScanStatus for scan-specific state going forward.
 */
export type BuildingStatus = 'draft' | 'scanned' | 'published';

// ---------------------------------------------------------------------------
// Building — Model
// ---------------------------------------------------------------------------

/**
 * Represents a physical indoor building managed by the application.
 *
 * Phase 2 additions: address, buildingType, scanStatus, thumbnailUri.
 */
export interface Building {
  /** Unique identifier (generated by buildingService). */
  id: string;
  /** Human-readable name of the building. */
  name: string;
  /** Optional description. */
  description?: string;
  /** Physical address of the building. */
  address?: string;
  /** Category of the building. */
  buildingType: BuildingType;
  /** Number of floors. Min 1, max 100. */
  floorCount: number;
  /** Current scan status. */
  scanStatus: ScanStatus;
  /** Legacy status field (kept for Phase 1 compatibility). */
  status: BuildingStatus;
  /** Local URI of the building thumbnail image (Phase 2: placeholder only). */
  thumbnailUri?: string;
  /** ISO 8601 timestamp of creation. */
  createdAt: string;
  /** ISO 8601 timestamp of last update. */
  updatedAt: string;
}

/**
 * Payload for creating a new building.
 */
export interface CreateBuildingPayload {
  name: string;
  description?: string;
  address?: string;
  buildingType: BuildingType;
  floorCount: number;
  thumbnailUri?: string;
}

/**
 * Payload for updating an existing building.
 * All fields are optional — only provided fields will be updated.
 */
export type UpdateBuildingPayload = Partial<Omit<Building, 'id' | 'createdAt'>>;

// ---------------------------------------------------------------------------
// Theme
// ---------------------------------------------------------------------------

/** Supported color scheme identifiers. */
export type ColorScheme = 'light' | 'dark';

// ---------------------------------------------------------------------------
// App State
// ---------------------------------------------------------------------------

/**
 * Global application configuration state stored in Zustand.
 */
export interface AppState {
  colorScheme: ColorScheme;
  splashShown: boolean;
  toggleColorScheme: () => void;
  setSplashShown: (value: boolean) => void;
}

// ---------------------------------------------------------------------------
// Building State
// ---------------------------------------------------------------------------

/**
 * Building-related state stored in Zustand.
 * Phase 2: Added updateBuilding, deleteBuilding, getBuildingById.
 */
export interface BuildingState {
  /** In-memory list of all buildings. */
  buildings: Building[];
  /** ID of the currently selected / viewed building. */
  selectedBuildingId: string | null;
  /** Whether a loading operation is in progress. */
  isLoading: boolean;
  /** Last error message, if any. */
  error: string | null;

  // ── Read ──────────────────────────────────────────────────────────────────
  /** Replace the full buildings list. */
  setBuildings: (buildings: Building[]) => void;

  // ── Create ────────────────────────────────────────────────────────────────
  /** Append a single building to the list. */
  addBuilding: (building: Building) => void;

  // ── Update ────────────────────────────────────────────────────────────────
  /** Update an existing building by ID. */
  updateBuilding: (id: string, payload: UpdateBuildingPayload) => void;

  // ── Delete ────────────────────────────────────────────────────────────────
  /** Remove a building from the list by ID. */
  deleteBuilding: (id: string) => void;

  // ── Selection ─────────────────────────────────────────────────────────────
  /** Set the currently selected building ID (null to deselect). */
  selectBuilding: (id: string | null) => void;

  // ── Status ────────────────────────────────────────────────────────────────
  setLoading: (value: boolean) => void;
  setError: (message: string | null) => void;
}

// ---------------------------------------------------------------------------
// Re-export Camera & AR & Scan Session & Plane & Walkthrough Types
// ---------------------------------------------------------------------------
export * from './camera';
export * from './ar';
export * from './arNative';
export * from './scanSession';
export * from './plane';
export * from './walkthrough';
export * from './buildingScanWorkflow';
export * from './coverage';
export * from './scanValidation';
export * from './buildingScanFinalization';
