/**
 * @file src/types/scanValidation.ts
 * @description Intelligent Scan Validation Engine TypeScript types and interfaces.
 */

import type { ARTrackingQuality } from './ar';

/**
 * Definite scan validation outcome classification.
 */
export type ScanValidationOutcome =
  | 'PASS'
  | 'PASS_WITH_WARNINGS'
  | 'INCOMPLETE'
  | 'FAILED';

/**
 * Configurable scan validation threshold parameters.
 */
export interface ScanValidationThresholds {
  /** Minimum required spatial coverage percentage (default 70%). */
  minCoveragePct: number;
  /** Minimum required 3D point cloud feature density (default 15 pts/m²). */
  minPointDensity: number;
  /** Minimum required detected physical surface planes (default 2). */
  minPlaneCount: number;
  /** Maximum allowable redundant walking percentage (default 50%). */
  maxRedundantScanPct: number;
  /** Minimum required walking distance in meters (default 10m). */
  minWalkDistanceMeters: number;
  /** Minimum tracking score percentage (default 70%). */
  minTrackingScore: number;
}

/**
 * 6-Factor Quality Scoring breakdown (0% - 100%).
 */
export interface ScanValidationScores {
  coverageScore: number;
  trackingScore: number;
  pointCloudScore: number;
  planeScore: number;
  movementScore: number;
  stabilityScore: number;
  overallScore: number;
}

/**
 * Complete evaluation report generated by Scan Validation Engine.
 */
export interface ScanValidationReportModel {
  /** Evaluation ID. */
  evaluationId: string;
  /** Session ID. */
  sessionId: string;
  /** Building ID. */
  buildingId: string;
  /** Building Name. */
  buildingName: string;
  /** Definite outcome (`PASS`, `PASS_WITH_WARNINGS`, `INCOMPLETE`, `FAILED`). */
  outcome: ScanValidationOutcome;
  /** Overall score percentage (0% - 100%). */
  overallScore: number;
  /** 6-Factor score breakdown. */
  scores: ScanValidationScores;
  /** List of detected validation warnings. */
  warnings: string[];
  /** List of actionable administrator rescan recommendations. */
  recommendations: string[];
  /** Thresholds configured during evaluation. */
  thresholdsUsed: ScanValidationThresholds;
  /** ISO string of evaluation timestamp. */
  timestamp: string;
}
